version: '2'
services:
  db:
    build: ./db/
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: TODO_DB
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
  # app:
  #   build: ./app/
  #   ports:
  #     - "8080:80"
  #   links:
  #     - db
  #   volumes:
  #     - ./src:/var/www/html
  #   stdin_open: true
  #   tty: true